### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by dabao1955** [NickTheHuy/CockPY#6]
# os version ubuntu22.10
# python verdion 3.11.0-rc3
# error logs
Exception in thread Thread-1 (run_http_server):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/CockPY/sdk_server/app.py", line 262, in run_http_server
    app.run(host=host, port="80", debug=True)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 767, in run
    run(self, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 3172, in run
    server.run(app)
  File "/usr/local/lib/python3.11/site-packages/bottle.py", line 2798, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.11/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/local/lib/python3.11/http/server.py", line 135, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/CockPY/game_server/json/excel/MaterialExcelConfigData.json' mode='r' encoding='UTF-8'>

**Comment by NickTheHuy** [comment]
seems like an issue with Ubuntu, i will look into it further.
for now i recommend using it on windows
